local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: odom
    robot_base_frame: base_link
    use_sim_time: False
    rolling_window: true
    width: 4
    height: 4
    resolution: 0.05
    robot_radius: 0.1
    plugins: ["voxel_layer"] 
    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: True
      publish_voxel_map: True
      origin_z: 0.0
      z_resolution: 0.05
      z_voxels: 16
      max_obstacle_height: 2.0
      mark_threshold: 0
      observation_sources: pointcloud
      pointcloud:
        topic: /depth/color/points
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        data_type: "PointCloud2"
    static_layer:
      map_subscribe_transient_local: True
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 1.0
      inflation_radius: 0.55
    always_send_full_costmap: True
local_costmap_client:
  ros__parameters:
    use_sim_time: False
local_costmap_rclcpp_node:
  ros__parameters:
    use_sim_time: False
