# rs_node:
#   ros__parameters:
#     device_type: ''
#     serial_no: ''
#     usb_port_id: ''

#     color_fps: 15.0
#     color_height: 480
#     color_width: 848
#     color_qos: "SENSOR_DATA"

#     depth_fps: 15.0
#     depth_height: 480
#     depth_width: 848
#     depth_qos: "SENSOR_DATA"

#     # infra_height: 480
#     # infra_width: 640
#     # infra_qos: "SENSOR_DATA"

#     gyro_fps: 400.0

#     enable_accel: true
#     enable_color: true
#     enable_depth: true
#     enable_gyro: true
#     enable_infra1: true
#     enable_infra2: true
#     enable_pointcloud: true
#     filters: ''


#     # pointcloud_texture_index: 
#     pointcloud_texture_stream: RS2_STREAM_COLOR

#     stereo_module:
#       emitter_enabled: 1
#     unite_imu_method: ''

#     rosbag_filename: ''
rs_node:
  ros__parameters:
    device_type: ''
    serial_no: ''
    usb_port_id: ''

    color_fps: 15.0
    color_height: 480
    color_width: 640
    color_qos: "SENSOR_DATA"

    depth_fps: 15.0
    depth_height: 480
    depth_width: 640
    depth_qos: "SENSOR_DATA"

    # infra_height: 480
    # infra_width: 640
    # infra_qos: "SENSOR_DATA"

    gyro_fps: 400.0

    enable_accel: true
    enable_color: true
    enable_depth: true
    enable_gyro: true
    enable_infra1: false
    enable_infra2: false
    enable_pointcloud: true
    filters: ''


    # pointcloud_texture_index: 
    pointcloud_texture_stream: RS2_STREAM_COLOR

    stereo_module:
      emitter_enabled: 1
    unite_imu_method: ''

    rosbag_filename: ''
